CREATE TABLE IF NOT EXISTS `ws_migrations_apply_changes_log` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `SETUP_LOG_ID` INT (11),
  `GROUP_LABEL` VARCHAR (128),
  `SOURCE` VARCHAR(50),
  `DATE` DATETIME NOT NULL,
  `PROCESS` VARCHAR (128) NOT NULL,
  `SUBJECT` VARCHAR (128) DEFAULT NULL,
  `UPDATE_DATA` MEDIUMTEXT NOT NULL,
  `ORIGINAL_DATA` MEDIUMTEXT DEFAULT NULL,
  `SUCCESS` INT (1),
  `DESCRIPTION` TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `ws_migrations_setups_log` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `USER_ID` INT,
  `DATE` DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS `ws_migrations_db_version_references` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `REFERENCE` VARCHAR (40),
  `DB_VERSION` VARCHAR(64),
  `GROUP` VARCHAR (64),
  `ITEM_ID` VARCHAR (32)
);
